version: '2.0'
notifications:
  notifier:
    espace:
      'on': false
    email:
      'on': false
buildspace:
  log_collect:
    - config/CI/build/logs
  fixed: true
env:
  resource:
    type: docker
    image: kweecr04.his.huawei.com:80/ecr-build-arm-gzkunpeng/euleros_v2r7spc522_x64_opmt_cs5.0_sz:v5.0
    class: 4U8G
    mode: toolbox
  cache:
    - type: workspace
steps:
  PRE_BUILD:
    - checkout:
        path: horizon-core
    - gitlab:
        url: https://szv-y.codehub.huawei.com/CloudSOP/CloudSOP-CI.git
        branch: $branch
        path: CI
  BUILD:
    - build_execute:
        command: |
          npm install yarn -g
          yarn config set strict-ssl false
          cd horizon-core
          yarn
          yarn run test
          yarn run build
          node .cloudbuild/release.js
        enhance:
          - feature: md5_source_tracement
            build_tools: [npm]
        check:
          auto: true
          buildcheck: true
          mode: sync
