version: '2.0'
notifications:
  notifier:
    espace:
      'on': false
    email:
      'on': false
buildspace:
  log_collect:
    - config/CI/build/logs
  fixed: true
env:
  resource:
    type: docker
    image: kweecr04.his.huawei.com:80/ecr-build-arm-gzkunpeng/euleros_v2r7spc522_x64_opmt_cs5.0_sz:v5.0
    class: 8U16G
    mode: toolbox
  cache:
    - type: workspace
steps:
  PRE_BUILD:
    - checkout:
        path: horizon-core
    - gitlab:
        url: https://szv-open.codehub.huawei.com/innersource/fenghuang/horizon/horizon-test.git
        branch: master
        path: horizon-test
  BUILD:
    - build_execute:
        command: |
          npm install yarn -g
          yarn config set strict-ssl false
          cd horizon-core
          yarn
          cd ../horizon-test
          yarn
          yarn run test
